### ISSUE TITLE
Empty repository after running the stack

### ISSUE THREAD

**Issue by ssp0** [oracle-devrel/terraform-oci-arch-devops-deployment-strategies#8]
I ran the RMS stack, which failed first due to a typo in the stack config but after a successful Apply, I noticed that the code repository was empty and had the following error "You have an empty repository". 

Any idea how to fix the issue?

**Comment by RahulMR42** [comment]
This is mostly due to an invalid or expired or less privileged user access token. Can you try pushing content to an OCI Code repo with your credentials and let us know?

To fix this you can 
- Delete the stack and use the deploy button again.
- Or use our repo/clone it your local and push it to the concerned OCIR.
- The repo information can be found from variables. tf files as below under the specific folder

**Comment by RahulMR42** [comment]
Closing as there is no further response/query
